### ISSUE TITLE
[Suggestion] Add this to builds page

### ISSUE THREAD

**Issue by Seggan** [kii-chan-reloaded/GeneticChickengineering#1]
Simple. Add this to TheBusyBiscuit's [builds page](github.com/TheBusyBiscuit/builds). Simply edit `repos.json` with your addon and PR. This will give you automatic builds (so no need for releases!)

**Comment by kii-chan-reloaded** [comment]
[Waiting on review!](https://github.com/TheBusyBiscuit/builds/pull/71) Thanks for the suggestion 😊
