### ISSUE TITLE
excitation chamber dupe

### ISSUE THREAD

**Issue by mrcoffee1026** [kii-chan-reloaded/GeneticChickengineering#11]
Happens if player mines their Excitation Chamber with an explosive pickaxe.  Chamber will drop items within... drop an excitation chamber... as well as stay in tact with original items still within: duping the chickens and whatever other inventory is within the chamber as well as the chamber itself.  Workaround for now is to blacklist "blast_chamber" in the explosive pickaxe item list (Items.yml), which will still cause inventory item to be dropped from the chamber, but the inventory is - in fact - actually also emptied so it is not a dupe.

[14:39:42 INFO]: This Server uses the following setup of Slimefun:
Paper git-Paper-505 (MC: 1.16.5)
Slimefun DEV - 825 (git 49950cf6)
Metrics-Module #21
Java 8

Installed Addons: (31)
  GlobalWarming vDEV - 9 (git d21d264b)
  ExtraTools vDEV - 25 (git 209f9078)
  FoxyMachines vDEV - 15 (git e62a72b8)
  SlimefunOreChunks vDEV - 13 (git 9f7a2be3)
  SensibleToolbox vDEV - 39 (git 9580549f)
  DynaTech vDEV - 48 (git 044b15b2)
  ExtraGear vDEV - 12 (git 4570ea2c)
  MoreTools vDEV - 10 (git 660e2ce6)
  InfinityExpansion vDEV - 84 (git fb607375)
  SFCalc vDEV - 15 (git 6586cb3f)
  ElectricSpawners vDEV - 22 (git 4cb2c56b)
  ExtraHeads vDEV - 21 (git a2c68d59)
  MobCapturer vDEV - 15 (git a42c9e0c)
  SlimyTreeTaps vDEV - 18 (git ab11a282)
  PrivateStorage vDEV - 16 (git f9468f23)
  TranscEndence vDEV - 23 (git c7ddc06a)
  GeneticChickengineering vDEV - 12 (git 8912d443)
  FluffyMachines vDEV - 67 (git d5ed4a58)
  CMI v8.8.1.5
  ChestTerminal vDEV - 42 (git f4aef9ca)
  DyedBackpacks vDEV - 14 (git 0a051b2b)
  SoundMuffler vDEV - 19 (git 5caef292)
  SlimefunWarfare vDEV - 19 (git 6b17971c)
  EcoPower vDEV - 3 (git 18ba903d)
  HotbarPets vDEV - 36 (git 71e1a5e7)
  SlimefunLuckyBlocks vDEV - 32 (git e108f086)
  ExoticGarden vDEV - 74 (git 3366e8ac)
  Liquid vDEV - 10 (git 2277a85b)
  LiteXpansion vDEV - 125 (git 96d1cf20)
  SoulJars vDEV - 22 (git aded79dd)
  SlimyRepair vDEV - 3 (git c56293bb)

**Comment by kii-chan-reloaded** [comment]
I set my test server to use your exact versions of Paper, Slimefun, and GCE, but [I can't seem to replicate this.](https://i.imgur.com/dqS3xjo.gifv) I can only get it to work as expected, which is the machine being destroyed, dropping itself, and ejecting its inventory with no duplication. I have a suspicion this is a bug from a different plugin, but I have no real hint as to what it could be.

If you have access to the server logs, would you see if there are any exceptions thrown when you try doing this on your server? I would like to take a look amd make sure my suspicion is correct before I close this.

**Comment by mrcoffee1026** [comment]
There wasn't one but adding the vanilla version of the block to the blacklist of the explosive pickaxe did resolve the duping so I'm just leaving it in there.  The only other plugin that interfaces with the block in any way might be Jobs?  I'm sure it registers smelted items for furnaces, maybe it attempts to do something like that with the blast chamber and tracks the inventory in some way but I'm only guessing here.
