### ISSUE TITLE
Water Eggs can be used in the Nether Dimension

### ISSUE THREAD

**Issue by CheesyOnion** [kii-chan-reloaded/GeneticChickengineering#12]
As the title states, Water Eggs are still usable in the Nether and the water does not dry up like I assume it should be.

Slimefun - DEV 864 + Version 1.2.0 of this addon are currently being used.

Thanks in advanced for any responses!

**Comment by kii-chan-reloaded** [comment]
Good catch! It slipped my mind to check for that when I wrote that code.
