### ISSUE TITLE
pocket chickens don't produce water or lava eggs

### ISSUE THREAD

**Issue by Boomer-1** [kii-chan-reloaded/GeneticChickengineering#5]
Maybe I'm missing something, but I have 2 pocket chickens, one in one excitation chamber, one in another, trying to get the water or lava eggs. After hundreds of feathers, i haven't had one show up yet. Is it truly that rare or is something up?

**Comment by Boomer-1** [comment]
wait, could I be that dumb.... i need both recessive genes right? it's not just putting a pocket chicken in the chamber....

**Comment by kii-chan-reloaded** [comment]
You're not dumb, the guide is a bit misleading on that front. I will work on making the guide less confusing, my apologies.

For what it's worth, the [wiki](https://github.com/kii-chan-reloaded/GeneticChickengineering/wiki) now has a *much* more in-depth explanation of how this mod works, so perhaps that will help with any further confusion?

**Comment by Boomer-1** [comment]
i love what you did with the wiki! it may be the best wiki on slimefun that i've seen!

**Comment by kii-chan-reloaded** [comment]
That is quite high praise, and I'm not quite sure that I deserve it... Thank you nonetheless!
