### ISSUE TITLE
Error when trying to use pocket chicken

### ISSUE THREAD

**Issue by bobhenl** [kii-chan-reloaded/GeneticChickengineering#6]
Hi, my player tried to use pocket chicken but he got this error:
https://pastebin.com/556Vngva

And it works as infinity spawner of chickens then, cause you can still right click with it to spawn chickens.

**Comment by kii-chan-reloaded** [comment]
Hm that shouldn't be happening... All pocket chicken items should get their DNA metadata set when they are created. Can you tell me more about how you got that particular chicken item (i.e. cheated, bred, captured, etc)? I think for now I'll release a patch that will just assign some random DNA to a chicken if the item somehow has no DNA. Should be ready in a bit after I do some testing.

I suppose now that I think about it some more, the Pocket Chicken item in the regular `Genetic Chickengineering` category of the book doesn't have any DNA assigned to it. Did you cheat this pocket chicken into your inventory from the `Genetic Chickengineering` Category in the book?

**Comment by bobhenl** [comment]
Hi, this chicken has been earnt normally, so I don't know why it happened, but we will see if it will help.
